### ISSUE TITLE
Mimics are spawning in `minecraft:the_void` biome

### ISSUE THREAD

**Issue by saltyseadoggo** [ReillyGregorio/ProbablyChests#15]
The superflat preset "The Void" uses the biome of the same name, and no vanilla mobs spawn in this biome. It would thus be expected that mimics would not spawn in this biome, but they are doing so, and infesting my testing world as a result. 
I would like to see them not spawn in `minecraft:the_void` biomes.
![2022-05-09_16 32 23](https://user-images.githubusercontent.com/69029346/167515066-d8f15f1f-c56b-4225-bf93-29ebddf6c423.png)

**Comment by ArcanePigeon** [comment]
Yes this is an issue I am working on right now, mimic spawning is all messed up, should be pushing an update as soon as a fix it.
