### ISSUE TITLE
Mimics spawn ignoring light conditions, including in homes and underground

### ISSUE THREAD

**Issue by unilock** [ReillyGregorio/ProbablyChests#17]
This is my basement.

![2022-06-07_10 00 06](https://user-images.githubusercontent.com/11802133/172399496-00771362-07fd-46f4-8c95-3b4a78aa4618.png)

As you can see, it's very well lit. As you can also see, mimics are spawning in it. This is very, very annoying.
Note that the basement has no exposure to the sky. And that mimics don't appear to be spawning in lit areas around the basement above ground?

[Light Overlay](https://www.curseforge.com/minecraft/mc-mods/light-overlay) shows that there are no blocks where aggressive mobs can spawn naturally.

I'd like for mimic spawns to respect lighting conditions, or at least for there to be a way to ward of mimics somehow, a la [Bewitchment's](https://www.curseforge.com/minecraft/mc-mods/bewitchment) god-foresaken ghosts and candelabras. (though the former would be much preferred)

**Comment by ArcanePigeon** [comment]
Please check that you are using the latest version of Probably Chests

**Comment by unilock** [comment]
I'm using `probablychests-0.4.3.jar`, which is the latest version on CurseForge.
Note that I'm playing the modpack [All of Fabric 5](https://github.com/TeamAOF/All-of-Fabric-5). I will test whether this still occurs with only Probably Chests installed.

**Comment by unilock** [comment]
It's hard to say for sure, but after removing the dirt ceiling in the screenshot above (there are bricks and glass above it), mimics seem to stop spawning entirely in the same world with just Probably Chests installed, and at least spawn much less frequently on AoF5. I'm not sure if this would still be considered an issue?
(Note that I didn't test the same world with the dirt ceiling still in place with only Probably Chests installed.)

Screenshot for reference.

![2022-06-08_05 35 43](https://user-images.githubusercontent.com/11802133/172584570-5747715a-44e3-4235-bc30-9507013d7df3.png)

**Comment by ArcanePigeon** [comment]
Ok, this sounds like it may be a compatibility issue with another mod. I will look into it as soon as I can.

**Comment by unilock** [comment]
Thanks so much for fixing this!

Now, this may be too much to ask, but would you be willing to backport the latest commit to 1.18.2? (or at least the light level check - for use in modpacks that are still on 1.18.2)

**Comment by ArcanePigeon** [comment]
I will try to get to that tomorrow if i'm no too busy.
