### ISSUE TITLE
Crash while loading game

### ISSUE THREAD

**Issue by DanDragonWolf** [ReillyGregorio/ProbablyChests#19]
The game gives a crash report and says that ProbablyChests causes an issue, but then my latest log file doesn't say anything that's shown in the crash log.

Here's my crash log: https://pastebin.com/A0DVMGDN

Here's my latest log: https://pastebin.com/73xAKU4e

**Comment by ArcanePigeon** [comment]
it says you are missing geckolib right at the top of the crash log

**Comment by DanDragonWolf** [comment]
If Geckolib is required, then you should add it to the dependencies on the CurseForge page.
