### ISSUE TITLE
Crash and a note: See description

### ISSUE THREAD

**Issue by Jack-Papel** [ReillyGregorio/ProbablyChests#2]
We've recently received a [crash report](https://github.com/devs-immortal/Paradise-Lost/issues/657) on our mod, Paradise Lost. When inspecting the logs, I saw that your mod caused the crash. I've linked the report so you can see what the issue is.

On top of that crash, I noticed one other issue. The log refers to your placed lush pot feature as 
`ResourceKey[minecraft:worldgen/placed_feature / minecraft:lush_pot_placed]`
with the Minecraft namespace instead of your own.
I would recommend you register them with your own namespace.

Thanks for reading. Have a good one.

**Comment by ArcanePigeon** [comment]
Thanks for letting me know. Do you currently have mods that modify the world height of either the overworld or the nether and how are they being modified?

**Comment by ArcanePigeon** [comment]
I just tested the mod with paradise lost and did not get the same error you did. in fact the error you got should be impossible as the piece of code it is referring to has a check that gets the absolute value before passing it into the random so I have no idea how that could be causing an error, and the mod should not be loading that placement feature inside the aether in the first place. I made a few changes to the way the placement modifier works so try the jar in this zip and see if the problem persists.
[probablychests-0.3.1.zip](https://github.com/ReillyGregorio/ProbablyChests/files/8500794/probablychests-0.3.1.zip)

**Comment by Jack-Papel** [comment]
@RogueZombieDog

**Comment by ArcanePigeon** [comment]
This bug has been fixed with the addition of a check of the bounds of the random to prevent errors. Release 0.3.1 has been uploaded to curseforge.

**Comment by RogueZombieDog** [comment]
> Thanks for letting me know. Do you currently have mods that modify the world height of either the overworld or the nether and how are they being modified?

if you still want to know, i have amplified nether installed which changes the nethers hight

**Comment by RogueZombieDog** [comment]
> I just tested the mod with paradise lost and did not get the same error you did. in fact the error you got should be impossible as the piece of code it is referring to has a check that gets the absolute value before passing it into the random so I have no idea how that could be causing an error, and the mod should not be loading that placement feature inside the aether in the first place. I made a few changes to the way the placement modifier works so try the jar in this zip and see if the problem persists. [probablychests-0.3.1.zip](https://github.com/ReillyGregorio/ProbablyChests/files/8500794/probablychests-0.3.1.zip)

oddly seem to still be crashing with the new version of the mod installed, ill send the logs if you need

**Comment by ArcanePigeon** [comment]
> > I just tested the mod with paradise lost and did not get the same error you did. in fact the error you got should be impossible as the piece of code it is referring to has a check that gets the absolute value before passing it into the random so I have no idea how that could be causing an error, and the mod should not be loading that placement feature inside the aether in the first place. I made a few changes to the way the placement modifier works so try the jar in this zip and see if the problem persists. [probablychests-0.3.1.zip](https://github.com/ReillyGregorio/ProbablyChests/files/8500794/probablychests-0.3.1.zip)
> 
> oddly seem to still be crashing with the new version of the mod installed, ill send the logs if you need

Did you try the latest version i pushed to curseforge? the one i sent you in that link still had the problem.

**Comment by RogueZombieDog** [comment]
> e i sent

oh not yet ill try it tomorrow

**Comment by KiritoKing** [comment]
> > > I just tested the mod with paradise lost and did not get the same error you did. in fact the error you got should be impossible as the piece of code it is referring to has a check that gets the absolute value before passing it into the random so I have no idea how that could be causing an error, and the mod should not be loading that placement feature inside the aether in the first place. I made a few changes to the way the placement modifier works so try the jar in this zip and see if the problem persists. [probablychests-0.3.1.zip](https://github.com/ReillyGregorio/ProbablyChests/files/8500794/probablychests-0.3.1.zip)
> > 
> > 
> > oddly seem to still be crashing with the new version of the mod installed, ill send the logs if you need
> 
> Did you try the latest version i pushed to curseforge? the one i sent you in that link still had the problem.

I'm sorry but I still met crash error when entering the aether dimension with ProbablyChest mod, while it goes right after i delete the mod even with the latest version(v-0.3.1)

![image](https://user-images.githubusercontent.com/19513548/164412909-8e2bae4e-5f31-4190-a8d1-80d0ee1032aa.png)
[minecraft-exported-crash-info-2022-04-21T16-25-31.zip](https://github.com/ReillyGregorio/ProbablyChests/files/8529130/minecraft-exported-crash-info-2022-04-21T16-25-31.zip)

**Comment by ArcanePigeon** [comment]
Alright that is weird. I will look into it in the morning.

**Comment by KiritoKing** [comment]
> Alright that is weird. I will look into it in the morning.

thx, look forward to your early reply.

**Comment by ArcanePigeon** [comment]
Could you make sure that you are using the 0.3.1 from curseforge and not the one i sent in the zip above? I looked at your crash log and it says it called the random on line 59 but that line number is what it was in the zip file and not the one i pushed to curseforge. The error you are getting is impossible in the proper version.
