### ISSUE TITLE
Built a house and mimics spawns are insane is there any way I can prevent them from spawning in the building?

### ISSUE THREAD

**Issue by P4nd4sBox** [ReillyGregorio/ProbablyChests#22]
So I built a house and it a bit on the bigger side and on every floor there's at least three of four mimics that spawn and when I wake up after sleeping they spawn and attack me and it makes it impossible to play with a house that I built I was just wondering if there was anyway I could prevent them from spawning around me?

**Comment by ArcanePigeon** [comment]
This is an issue with a light check which is fixed in the 1.19 version. I will be backporting this fix soon. In the meantime I recommend disabling natural mimic spawns in the config.

**Comment by P4nd4sBox** [comment]
okay thank you
