### ISSUE TITLE
Curseforge Download Issue

### ISSUE THREAD

**Issue by DDriggs00** [ReillyGregorio/ProbablyChests#23]
Something is preventing this mod from being downloaded as a part of a modpack on third-party launchers. This is typically caused by a misconfigured setting in Curseforge.

**Comment by ArcanePigeon** [comment]
This is intentional. The mod is not meant to be downloaded on launchers other than curseforge. If you would like that changed please tell me the modpack you are downloading and I'll see if I want to change the setting.

**Comment by DDriggs00** [comment]
I was referring to AOF5 in this instance.

**Comment by DDriggs00** [comment]
Also, here's a more detailed appeal written by someone with a bit more experience than me: https://gist.github.com/copygirl/7d45bad739453d2be61138cebafce04c

**Comment by ArcanePigeon** [comment]
The mod can now be downloaded outside of curse.
