### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'probablychests'!

### ISSUE THREAD

**Issue by LordOfTheWeebs** [ReillyGregorio/ProbablyChests#24]
When attempting to load ProbablyChests on my Fabric 1.19 client, the game never fully boots. The launcher closes and then it re-opens with the attached crash report. I have tested it in a clean modded client with only ProbablyChests and its Fabric API dependency just in case it was an issue with one of the other mods I'm using. I'm not sure what the issue could be caused by as I'm not adept with programming, though the only tests I haven't run are using previous versions of Fabric and the Fabric API. I'm currently using the latest of both for 1.19 (0.14.8-1.19 and 0.57.0-1.19 respectively).

The crash report:
[crash-2022-07-04_22.10.00-client.txt](https://github.com/ReillyGregorio/ProbablyChests/files/9042776/crash-2022-07-04_22.10.00-client.txt)

**Comment by ArcanePigeon** [comment]
Geckolib is required for the mod to work
