### ISSUE TITLE
How would this interact with Lootr Mod?

### ISSUE THREAD

**Issue by Soggyshorts** [ReillyGregorio/ProbablyChests#29]
I love the idea of your mod, but we are already using [Lootr ](https://www.curseforge.com/minecraft/mc-mods/lootr-fabric)  which we very much enjoy, and I'm not sure how mimics, locked chests, and player-specific loot can work together.  Ideally, I suppose mimics would just turn into regular chests when killed, that way we could both still loot them.

Thanks!

**Comment by ArcanePigeon** [comment]
I am not certain if i will use lootr's system or make my own version of instanced player loot when i get around to that update, The idea would be after the first player interacts with the chest it will decide if it is a mimic and if it is not then it would work like any other lootr chest using my loot tables.

**Comment by ArcanePigeon** [comment]
also for discussing the mod please join the discord instead of creating issues on the github.
