### ISSUE TITLE
Crash with Revamped Phantoms mod

### ISSUE THREAD

**Issue by sirben99** [ReillyGregorio/ProbablyChests#30]
Hey!

I had an crash where a phantom picked up a mimic. Revamped Phantoms mod makes it so they can pickup mobs and fly away with them, then drop them to the ground. I have made an issue on Revamped Phantoms issue tracker too, just incase its on theyr end.

Mod link: https://www.curseforge.com/minecraft/mc-mods/revamped-phantoms

ProbablyChests version: 1.18.2-0.5.1
Revamped Phantoms version: 1.18.2-0.2.3

Crash:
[crash-reports_crash-2022-07-21_20.26.08-server.txt](https://github.com/ReillyGregorio/ProbablyChests/files/9162648/crash-reports_crash-2022-07-21_20.26.08-server.txt)

**Comment by ArcanePigeon** [comment]
I have been unable to fix this no matter what I try. I believe this is an issue on their end.
