### ISSUE TITLE
Pet Mimics' animations don't work properly with shaders

### ISSUE THREAD

**Issue by FumpleWumper** [ReillyGregorio/ProbablyChests#34]
While wild Mimics play their animations correctly while using shaders, Pet Mimics don't play their animations at all, but as soon as shaders are disabled, they begin functioning properly

**Comment by ArcanePigeon** [comment]
This is an issue with geckolib and iris that I cannot fix caused by things like the entity shadows feature in shaders. I found that disabling entity shadows in the shader config fixes it.
