### ISSUE TITLE
Tamed Mimics act weird in water, disappear and no death message

### ISSUE THREAD

**Issue by ETTRAN777** [ReillyGregorio/ProbablyChests#36]
I tried teleporting my mimic to me using /tp @e[type=probablychests:normal_chest_mimic_pet] @s and every other variant of tamed mimics, but no entity was found, I assume that means its dead, but no death message was displayed. This happened at sea so I assume there is either no death message at all, or there is a glitch where pet mimics may disappear at sea. It also was seen swimming away from me rather than toward me after my boat was broken.

**Comment by ArcanePigeon** [comment]
If it is not loaded it can not be teleported, this is a base minecraft mechanic. It is just in a unloaded chunk and not a bug. and The mimic swimming bug is already a issue. please check other issues before posting.
