### ISSUE TITLE
Lots of Mimics

### ISSUE THREAD

**Issue by 74N3Harvey** [ReillyGregorio/ProbablyChests#38]
This is happening in my friend's survival server. Mimics and Chests are spawning rapidly next to his base. The red dots on my minimap are all Mimics. I have no idea what's causing this.   (Also this is my first time ever using the website. I have no idea what I'm doing)

Edit: Also would like to add, its not just normal mimics, Desert, Deepslate, Ocean, normal ones, they're all spawning there

![image](https://user-images.githubusercontent.com/112629610/187912069-777464db-68c7-4e3c-a3d5-12ec6e37c910.png)

**Comment by ArcanePigeon** [comment]
Could you send me the mod version number and the list of mods installed.

**Comment by 74N3Harvey** [comment]
> Could you send me the mod version number and the list of mods installed.

https://www.curseforge.com/minecraft/modpacks/medieval-mc-forge Here's the modpack and the version is 0.5.3

**Comment by ArcanePigeon** [comment]
Can you check what the mimic spawn rate is inside of the config? Also are any other mobs spawning in excess and is it localized to just his base or does it happen other places too?

**Comment by 74N3Harvey** [comment]
Sorry about the late reply, the only one who can check the configs went to sleep. From what we can see its just the 2 biomes next to his base and no other mobs are spawning at this rate, just the mimics

![image](https://user-images.githubusercontent.com/112629610/188151141-f43fedaf-79ca-4d09-9813-8dd4f779a682.png)

**Comment by ArcanePigeon** [comment]
What biomes? would it be possible to get some screenshots of the area and some underground in spectator mode? It may be an issue with a mods mob proofing or dungeon spawners.

**Comment by 74N3Harvey** [comment]
Hey, sadly we can't do anymore testing. The owner decided to turn off the ability for mimics to spawn cause they were not nice to the players, the biome answer though was Svanna.
