### ISSUE TITLE
Tamed mimic teleportation

### ISSUE THREAD

**Issue by staviq** [ReillyGregorio/ProbablyChests#41]
If you teleport, friendly mimic that was following you will be left behind permanently, until you return there.

This also seems to happen sometimes, when the tamed mimic simple gets stuck, and the player runs away fast enough.

This is likely because chunks get unloaded when player teleports, for example with a waystones.

If i manually claim and forceload a chunk, and then teleport, the mimic will teleport with me, if however I teleport from a non force-loaded chunk, mimic stays there and appears to get unloaded with the chunk.

Possible solution: some sort of soft force-chunkloading, such that chunks with tamed mimics will tick periodically.

**Comment by ArcanePigeon** [comment]
This is just a problem with teleportation and whatever mod you are using unloading the chunk before the mimic can tick. Adding a tick for an unloaded chunk would only cause extra lag for such a small thing so this issue will not be fixed

**Comment by staviq** [comment]
Since this creates a situation where literally every other mod with teleportation would have to add compatibility with this one, and it's completely unrealistic,

Can I at least suggest adding an item that would force summon tamed mimic ? Something like a "mimic whistle" maybe ?

**Comment by ArcanePigeon** [comment]
I looked into adding that initially as part of the mimic bell but the mimics are in unloaded chunks which just causes issues so I did not add it. My mods are currently on pause while I work on another project so I may look into something in the future but not any time soon.

**Comment by staviq** [comment]
Ok, thank you for considering my suggestion.
