### ISSUE TITLE
Add to Modrinth

### ISSUE THREAD

**Issue by sylv256** [ReillyGregorio/ProbablyChests#47]
Please consider adding this mod to Modrinth to make it easier for modpack creators etc. on Modrinth.
An increasing number of mods are moving to Modrinth, especially as they recently added monetization support. Modrinth is a platform with better searching, API, and features for mod developers, and their community and developers are very welcoming to developers.

**Comment by ArcanePigeon** [comment]
eventually I will move but at this point it is not worth it to put the time into maintaining 2 pages for all my mods.
