### ISSUE TITLE
Mimic damage inconsistency & Suffocation

### ISSUE THREAD

**Issue by CuriousGamer2** [ReillyGregorio/ProbablyChests#6]
So I was just testing if smite would give more damage to mimic chest, didn't seem liked it so I tried using sharpness and it killed the mimic instantly. I was quite surprised, I decided to try it again but this time it didn't. Probably because I hit the previous mimic with my smite V diamond sword before using the sharpness one. I tried doing that again but nope, it didn't work either.

Enchanted Diamond sword #1

Sharpness V
Fire aspect II
Knockback II

Enchanted Diamond sword#2
Smite V
Fire Aspect II
Knockback II

And when a mimic gets stuck in a wall, they don't seem to suffocate? For some reason. I could be wrong and just not hearing their hurting noises

It's not really a serious bug that would prevent a player from playing the mod, I don't really mind it either just felt like I should report so here we are.

**Comment by ArcanePigeon** [comment]
Mimic suffocation functions as intended. Could not reproduce damage inconsistency. No bug found.
