### ISSUE TITLE
Using Pet Mimic Key duplicated the mimic

### ISSUE THREAD

**Issue by Sus2129** [ReillyGregorio/ProbablyChests#7]
When using the key on a chest (which interacts will become a mimic), it becomes 2 mimics (a pet one and a normal one)

![image](https://user-images.githubusercontent.com/58522357/166449167-056a3a19-ce6c-427d-be6c-0d683c418161.png)

**Comment by ArcanePigeon** [comment]
Thank you for letting me know, This is an issue with using a pet mimic key on a chest that was already marked as a mimic. I have fixed the issue and will be pushing a new version now.
